DROP TABLE IF EXISTS result;
DROP TABLE IF EXISTS trade_card;
DROP TABLE IF EXISTS trade;
DROP TABLE IF EXISTS event_registration;
DROP TABLE IF EXISTS deck;
DROP TABLE IF EXISTS player_card;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS card;
DROP TABLE IF EXISTS player;

CREATE TABLE player (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'PLAYER',
    collection_visibility VARCHAR(20) NOT NULL DEFAULT 'TRADE_ONLY'
);

CREATE TABLE card (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    card_type VARCHAR(20) NOT NULL,
    color VARCHAR(20) NOT NULL,
    set_name VARCHAR(100) NOT NULL,
    rarity VARCHAR(20) NOT NULL,
    rule_text TEXT NULL,
    image_url VARCHAR(255) NULL
);

CREATE TABLE player_card (
    id INT PRIMARY KEY AUTO_INCREMENT,
    player_id INT NOT NULL,
    card_id INT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    for_trade BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (player_id) REFERENCES player(id) ON DELETE CASCADE,
    FOREIGN KEY (card_id) REFERENCES card(id) ON DELETE CASCADE
);

CREATE TABLE deck (
    id INT PRIMARY KEY AUTO_INCREMENT,
    player_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    format VARCHAR(20) NOT NULL,
    visibility VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
    FOREIGN KEY (player_id) REFERENCES player(id) ON DELETE CASCADE
);

CREATE TABLE event (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    location VARCHAR(100) NOT NULL,
    date DATE NOT NULL,
    format VARCHAR(20) NOT NULL,
    max_players INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'UPCOMING'
);

CREATE TABLE event_registration (
    id INT PRIMARY KEY AUTO_INCREMENT,
    player_id INT NOT NULL,
    event_id INT NOT NULL,
    deck_id INT NOT NULL,
    registration_date DATE NOT NULL,
    FOREIGN KEY (player_id) REFERENCES player(id) ON DELETE CASCADE,
    FOREIGN KEY (event_id) REFERENCES event(id) ON DELETE CASCADE,
    FOREIGN KEY (deck_id) REFERENCES deck(id) ON DELETE CASCADE
);

CREATE TABLE trade (
    id INT PRIMARY KEY AUTO_INCREMENT,
    proposer_id INT NOT NULL,
    receiver_id INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    FOREIGN KEY (proposer_id) REFERENCES player(id) ON DELETE CASCADE,
    FOREIGN KEY (receiver_id) REFERENCES player(id) ON DELETE CASCADE
);

CREATE TABLE trade_card (
    id INT PRIMARY KEY AUTO_INCREMENT,
    trade_id INT NOT NULL,
    player_card_id INT NOT NULL,
    role VARCHAR(20) NOT NULL,
    FOREIGN KEY (trade_id) REFERENCES trade(id) ON DELETE CASCADE,
    FOREIGN KEY (player_card_id) REFERENCES player_card(id) ON DELETE CASCADE
);

CREATE TABLE result (
    id INT PRIMARY KEY AUTO_INCREMENT,
    player_id INT NOT NULL,
    event_id INT NOT NULL,
    placement INT NOT NULL,
    FOREIGN KEY (player_id) REFERENCES player(id) ON DELETE CASCADE,
    FOREIGN KEY (event_id) REFERENCES event(id) ON DELETE CASCADE
);